# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deployDev:
    docker:
      # specify the version you desire here
      - image: node:10.15.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Meteor
          command: |
            apt-get update
            curl https://install.meteor.com/ | sh
            export METEOR_ALLOW_SUPERUSER=true

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            meteor npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn test
      - run:
          name: Install MUP
          command: |
            npm install --global mup
      - run:
          name: Deploying with MUP
          command: |
            cd .deployment
            METEOR_ALLOW_SUPERUSER=true mup deploy --verbose

workflows:
  version: 2
  build-deploy:
    jobs:
      - deployDev:
          filters:
            branches:
              only:
                - develop
